1c3s5z:       [9, 9, 5]
2m_vs_1z:     [2, 1, 5]
# 2s_vs_1sc:    [2, 1, 6]
2s3z:         [5, 5, 5]
3m:           [3, 3, 5]
3s_vs_3z:     [3, 3, 6]
3s_vs_4z:     [3, 4, 6]
8m:           [8, 8, 5]
3s_vs_5z:     [3, 5, 6]
3s5z:         [8, 8, 5]
5m_vs_6m:     [5, 6, 5]
8m_vs_9m:     [8, 9, 5]
10m_vs_11m:   [10, 11, 5]
25m:          [25, 25, 5]
# 2c_vs_64zg:   [2, 64, 6]
3s5z_vs_3s6z: [8, 9, 8]
6h_vs_8z:     [6, 8, 5]
27m_vs_30m:   [27, 30, 5]
bane_vs_bane: [24, 24, 7]
corridor:     [6, 24, 5]
MMM2:         [10, 12, 5]